# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Projects/Casioproject/Casio/Casio/Casio.cache/wt [current_project]
set_property parent.project_path C:/Projects/Casioproject/Casio/Casio/Casio.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_output_repo c:/Projects/Casioproject/Casio/Casio/Casio.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Projects/Casioproject/Casio/Casio/Casio.srcs/sources_1/bd/Casio_Design/hdl/Casio_Design_wrapper.v
add_files C:/Projects/Casioproject/Casio/Casio/Casio.srcs/sources_1/bd/Casio_Design/Casio_Design.bd
set_property used_in_implementation false [get_files -all c:/Projects/Casioproject/Casio/Casio/Casio.srcs/sources_1/bd/Casio_Design/ip/Casio_Design_processing_system7_0_0/Casio_Design_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/Casioproject/Casio/Casio/Casio.srcs/sources_1/bd/Casio_Design/ip/Casio_Design_axi_gpio_0_0/Casio_Design_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/Casioproject/Casio/Casio/Casio.srcs/sources_1/bd/Casio_Design/ip/Casio_Design_axi_gpio_0_0/Casio_Design_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/Casioproject/Casio/Casio/Casio.srcs/sources_1/bd/Casio_Design/ip/Casio_Design_axi_gpio_0_0/Casio_Design_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/Casioproject/Casio/Casio/Casio.srcs/sources_1/bd/Casio_Design/ip/Casio_Design_axi_gpio_1_1/Casio_Design_axi_gpio_1_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/Casioproject/Casio/Casio/Casio.srcs/sources_1/bd/Casio_Design/ip/Casio_Design_axi_gpio_1_1/Casio_Design_axi_gpio_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/Casioproject/Casio/Casio/Casio.srcs/sources_1/bd/Casio_Design/ip/Casio_Design_axi_gpio_1_1/Casio_Design_axi_gpio_1_1.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/Casioproject/Casio/Casio/Casio.srcs/sources_1/bd/Casio_Design/ip/Casio_Design_rst_ps7_0_100M_1/Casio_Design_rst_ps7_0_100M_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/Casioproject/Casio/Casio/Casio.srcs/sources_1/bd/Casio_Design/ip/Casio_Design_rst_ps7_0_100M_1/Casio_Design_rst_ps7_0_100M_1.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/Casioproject/Casio/Casio/Casio.srcs/sources_1/bd/Casio_Design/ip/Casio_Design_rst_ps7_0_100M_1/Casio_Design_rst_ps7_0_100M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/Casioproject/Casio/Casio/Casio.srcs/sources_1/bd/Casio_Design/ip/Casio_Design_xbar_0/Casio_Design_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/Casioproject/Casio/Casio/Casio.srcs/sources_1/bd/Casio_Design/ip/Casio_Design_axi_timer_0_0/Casio_Design_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/Casioproject/Casio/Casio/Casio.srcs/sources_1/bd/Casio_Design/ip/Casio_Design_axi_timer_0_0/Casio_Design_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/Casioproject/Casio/Casio/Casio.srcs/sources_1/bd/Casio_Design/ip/Casio_Design_axi_gpio_2_0/Casio_Design_axi_gpio_2_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/Casioproject/Casio/Casio/Casio.srcs/sources_1/bd/Casio_Design/ip/Casio_Design_axi_gpio_2_0/Casio_Design_axi_gpio_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/Casioproject/Casio/Casio/Casio.srcs/sources_1/bd/Casio_Design/ip/Casio_Design_axi_gpio_2_0/Casio_Design_axi_gpio_2_0.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/Casioproject/Casio/Casio/Casio.srcs/sources_1/bd/Casio_Design/ip/Casio_Design_auto_pc_0/Casio_Design_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Projects/Casioproject/Casio/Casio/Casio.srcs/sources_1/bd/Casio_Design/Casio_Design_ooc.xdc]
set_property is_locked true [get_files C:/Projects/Casioproject/Casio/Casio/Casio.srcs/sources_1/bd/Casio_Design/Casio_Design.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top Casio_Design_wrapper -part xc7z010clg400-1


write_checkpoint -force -noxdef Casio_Design_wrapper.dcp

catch { report_utilization -file Casio_Design_wrapper_utilization_synth.rpt -pb Casio_Design_wrapper_utilization_synth.pb }
