# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Casio_Design/Casio_Design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Casio_Design || ORIG_REF_NAME==Casio_Design}]

# IP: bd/Casio_Design/ip/Casio_Design_processing_system7_0_0/Casio_Design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Casio_Design_processing_system7_0_0 || ORIG_REF_NAME==Casio_Design_processing_system7_0_0}]

# IP: bd/Casio_Design/ip/Casio_Design_axi_gpio_0_0/Casio_Design_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Casio_Design_axi_gpio_0_0 || ORIG_REF_NAME==Casio_Design_axi_gpio_0_0}]

# IP: bd/Casio_Design/ip/Casio_Design_axi_gpio_1_1/Casio_Design_axi_gpio_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Casio_Design_axi_gpio_1_1 || ORIG_REF_NAME==Casio_Design_axi_gpio_1_1}]

# IP: bd/Casio_Design/ip/Casio_Design_ps7_0_axi_periph_1/Casio_Design_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Casio_Design_ps7_0_axi_periph_1 || ORIG_REF_NAME==Casio_Design_ps7_0_axi_periph_1}]

# IP: bd/Casio_Design/ip/Casio_Design_rst_ps7_0_100M_1/Casio_Design_rst_ps7_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Casio_Design_rst_ps7_0_100M_1 || ORIG_REF_NAME==Casio_Design_rst_ps7_0_100M_1}]

# IP: bd/Casio_Design/ip/Casio_Design_xbar_0/Casio_Design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Casio_Design_xbar_0 || ORIG_REF_NAME==Casio_Design_xbar_0}]

# IP: bd/Casio_Design/ip/Casio_Design_axi_timer_0_0/Casio_Design_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Casio_Design_axi_timer_0_0 || ORIG_REF_NAME==Casio_Design_axi_timer_0_0}]

# IP: bd/Casio_Design/ip/Casio_Design_xlconcat_0_0/Casio_Design_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Casio_Design_xlconcat_0_0 || ORIG_REF_NAME==Casio_Design_xlconcat_0_0}]

# IP: bd/Casio_Design/ip/Casio_Design_axi_gpio_2_0/Casio_Design_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Casio_Design_axi_gpio_2_0 || ORIG_REF_NAME==Casio_Design_axi_gpio_2_0}]

# IP: bd/Casio_Design/ip/Casio_Design_auto_pc_0/Casio_Design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Casio_Design_auto_pc_0 || ORIG_REF_NAME==Casio_Design_auto_pc_0}]

# XDC: bd/Casio_Design/Casio_Design_ooc.xdc
